"use client";
import Link from "next/link";
import { ArrowLeft, CalendarDays, GraduationCap, MapPin, Pencil, UsersRound, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { CurrentUserAccess } from "@/lib/auth/access";
import { cn } from "@/lib/utils";
import type { MobilityDetail } from "./mobility-query";
import { MobilityWorkflowActions } from "./mobility-workflow-actions";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(new Date(value)) : "ยังไม่ระบุ";
const workflow: Record<string, string> = { draft: "ร่าง", under_review: "รอตรวจสอบ", approved: "อนุมัติแล้ว", active: "กำลังดำเนินการ", completed: "เสร็จสิ้น", cancelled: "ยกเลิก", archived: "เก็บถาวร" };
export function MobilityDetailView({ mobility, access }: { mobility: MobilityDetail; access: CurrentUserAccess }) {
  return <main className="module-main"><div className="module-page-heading"><div><Link className="back-link" href="/mobility"><ArrowLeft /> กลับไปรายการ Mobility</Link><p className="module-eyebrow">Mobility นิสิต</p><h1>{mobility.project_name}</h1><p>{mobility.title_en || mobility.partner_name_snapshot || "ข้อมูล Mobility ภายใน"}</p></div><div className="flex flex-col items-end gap-2">{access.modules.mobility?.update && mobility.workflow_status === "draft" ? <Link className={cn(buttonVariants({ size: "lg" }))} href={`/mobility/${mobility.id}/edit`}><Pencil /> แก้ไขร่าง</Link> : null}<MobilityWorkflowActions id={mobility.id} updatedAt={mobility.updated_at} workflowStatus={mobility.workflow_status} access={access} /></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6"><Card><CardHeader><CardTitle className="flex items-center gap-2"><GraduationCap /> ข้อมูลโครงการ</CardTitle></CardHeader><CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><Info label="สถานะ"><Badge>{workflow[mobility.workflow_status]}</Badge></Info><Info label="ปีงบประมาณ">{mobility.fiscal_year || "-"}</Info><Info label="ทิศทาง">{mobility.direction}</Info><Info label="รูปแบบ Mobility">{mobility.mobility_mode || "-"}</Info><Info label="วัตถุประสงค์" wide>{mobility.purpose || "-"}</Info><Info label="เลขอ้างอิงอนุมัติ">{mobility.approval_reference || "-"}</Info></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin /> ปลายทางและกำหนดการ</CardTitle></CardHeader><CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><Info label="องค์กรคู่ความร่วมมือ">{mobility.partner_name_snapshot || mobility.partner_organizations?.name_th || mobility.partner_organizations?.name_en || "ยังไม่ระบุ"}</Info><Info label="ประเทศ / เมือง">{mobility.country_name_snapshot || mobility.countries?.name_th || "ยังไม่ระบุ"}{mobility.city ? ` / ${mobility.city}` : ""}</Info><Info label="วันเดินทาง"><span className="inline-flex gap-1 items-center"><CalendarDays className="w-4" />{date(mobility.start_date)} – {date(mobility.end_date)}</span></Info><Info label="เวลาการเดินทาง">{mobility.departure_at ? new Date(mobility.departure_at).toLocaleString("th-TH") : "-"} – {mobility.return_at ? new Date(mobility.return_at).toLocaleString("th-TH") : "-"}</Info></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><UsersRound /> ผู้เข้าร่วม ({mobility.movement_participants.length})</CardTitle></CardHeader><CardContent className="space-y-3">{mobility.movement_participants.length ? mobility.movement_participants.map((person) => <div className="border-b border-border pb-3 last:border-0 last:pb-0" key={person.id}><strong>{person.full_name_snapshot}</strong><p className="text-sm text-muted-foreground">{[person.student_id_snapshot, person.faculty_snapshot, person.study_program_snapshot, person.study_level_snapshot].filter(Boolean).join(" · ") || "ยังไม่ระบุรายละเอียด"}</p></div>) : <p className="text-sm text-muted-foreground">ยังไม่มีผู้เข้าร่วม</p>}</CardContent></Card></div>
      <div className="space-y-6"><Card><CardHeader><CardTitle className="flex items-center gap-2"><WalletCards /> งบประมาณ</CardTitle></CardHeader><CardContent className="space-y-3">{mobility.movement_funding.length ? mobility.movement_funding.map((fund) => <div key={fund.id}><strong>{fund.budget_type}</strong><p className="text-sm text-muted-foreground">{fund.source_name || "ไม่ระบุแหล่ง"} · {fund.amount?.toLocaleString() ?? "-"} {fund.currency}</p></div>) : <p className="text-sm text-muted-foreground">ยังไม่มีข้อมูลงบประมาณ</p>}</CardContent></Card><Card><CardHeader><CardTitle>ประวัติ Workflow</CardTitle></CardHeader><CardContent className="space-y-4">{mobility.movement_workflow_events.map((event) => <div className="border-l-2 border-primary pl-3" key={event.id}><strong className="text-sm">{workflow[event.to_status || ""] || event.action}</strong><p className="text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString("th-TH")} · {event.profiles?.display_name || event.profiles?.email || "ระบบ"}</p>{event.note ? <p className="text-xs mt-1">{event.note}</p> : null}</div>)}</CardContent></Card></div></div>
  </main>;
}
function Info({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <div className={wide ? "sm:col-span-2" : ""}><span className="block text-xs text-muted-foreground mb-1">{label}</span><div className="font-medium">{children}</div></div>; }
